# Generated by Django 4.1.1 on 2022-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_finch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='feathers',
            field=models.ManyToManyField(to='main_app.feathercolors'),
        ),
    ]
