# Generated by Django 4.1.1 on 2022-10-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_finch_feathers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feathercolors',
            new_name='Feather',
        ),
    ]
