# Generated by Django 4.1.1 on 2022-10-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_sightings_sighting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feather',
            name='name',
        ),
        migrations.RemoveField(
            model_name='finch',
            name='feathers',
        ),
        migrations.AddField(
            model_name='feather',
            name='finch',
            field=models.ManyToManyField(to='main_app.finch'),
        ),
    ]
